[package]
name = "pgimporter"
version = "0.1.0"
authors = ["Miguel Rivero <charrinton@gmail.com>"]
edition = "2018"

[dependencies]
dialoguer = "0.5.0"
postgres = "0.17.2"
chrono = "0.4.11"
indicatif = "0.14.0"
resolve = "0.2.0"
log = "0.4.8"
simple-logging = "2.0.2"

# Include all default features and also "postgres" implementation of Decimal
[dependencies.rust_decimal]
version = "1.4.1"
default-features = true
features = ["postgres"]