name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-import:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: rust:latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres-source:
        # Docker Hub image
        image: postgres:12
        env:
          # Provide the password for postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      # Label used to access the service container
      postgres-target:
        # Docker Hub image
        image: postgres:12
        env:
          # Provide the password for postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Download source code and build debug version
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      
      - name: Update APT
        run: apt update
      
      - name: Install PostgreSQL client
        run: apt install -y postgresql-client
      
      - name: Insert Test data in Source DB
        run: cd tests/ci; ./test.sh postgres-source 5432 postgres-target 5432; cd ../..
      
      - name: Import all data from source to target
        run: ./target/debug/pgimporter -s postgres:postgres@postgres-source:5432/postgres -t postgres:postgres@postgres-target:5432/postgres --batch-filename=tests/ci/test.yml
      
      - name: Check imported data with integration test
        run: cargo test -- --nocapture
